### ISSUE TITLE
Licence Breach

### ISSUE THREAD

**Issue by Wild1145** [LoopFreedom/LoopFreedomMod#1]
Under section 2.6 of the TF Development General Licence, you are required to retain an original copy of the licence. You have failed to do this and are currently in breach of the licence.

Please make the appropriate changes to your project to conform with the TF Licence.

**Comment by Nobody-11** [comment]
@looperXD  (Its your mod)

**Comment by LoopFreedom** [comment]
@Wild1145  I have made change as much as I can, and I added you as Collaborator , If I left something unchanged you could change it. You are more then welcome to change thing around.
