### ISSUE TITLE
Copyright Infringement

### ISSUE THREAD

**Issue by tylerhyperHD** [LoopFreedom/LoopFreedomMod#3]
Hello,

It has come to my attention that this repository contains copyrighted material in violation of a separate plugin license. The material in question is released under the TylerUtilsMod License [Version 1.0](https://github.com/tylerhyperHD/TylerUtilsMod/blob/master/LICENSE.md). It has come to our attention that the following content has similar properties and/or proportions to it:
-https://github.com/LoopFreedom/LoopFreedomMod/blob/master/src/me/StevenLawson/TotalFreedomMod/Commands/Command_relog.java

This is similar to the /relogger command in the TylerUtilsMod, which is against our license. 
Since you are under the TFGL license, you must remove the content immediately or fork the TylerUtilsMod.

I hope to have properly and sufficiently informed you of the violations in this repository. If you have any further questions, don't hesitate to contact me.

Thanks in advance,
Tyler Hyper

**Comment by StevenLawson** [comment]
Might I just say, this claim really doesn't fly. When I originally released TFM, I set the terms of the license so that any derivation of TFM's source code would remain open source. The only restrictions that apply to anything that has been based on TFM code are stated in the TFGL, which primarily pertain to binary distribution.

**Comment by tylerhyperHD** [comment]
This isn't a derivation of it. This is a completely separate plugin that just runs alongside it and doesn't necessarily "derive" from it.

**Comment by Nobody-11** [comment]
@looperXD

**Comment by falceso** [comment]
OFT: um I never thought @tylerhyperHD was part of tfm.. 
OTT: Btw we got a copyright Fragment by someone. I forgot..

**Comment by falceso** [comment]
Added Tags
@tylerhyperHD  would you like to be assigned to this.

**Comment by Wild1145** [comment]
This has not breached the TFM licence (As its not a TF Project) and also has not breached your own license (That you clearly copied from the TFM licence) as the authors have not been mis-represented or otherwise.

**Comment by Nobody-11** [comment]
What @Wild1145 has said.

**Comment by tylerhyperHD** [comment]
Wow you guys never read the fine print -_-

**Comment by tylerhyperHD** [comment]
Plus this is not a duplicated license, it has been modified.

**Comment by LoopFreedom** [comment]
@tylerhyperHD your utils was created in march 3rd.  LoopFreedomMod was created in feb 28. There is no way i could copy code unless you believe in time machine

**Comment by tylerhyperHD** [comment]
As stated in the license, "You may not remove any credits of any sort from the source of any project. These credits include but may not be limited to tylerhyperHD, the lead developer of the TylerUtilsMod."

**Comment by tylerhyperHD** [comment]
This was sub licensed since February, and has been moved to the TylerUtilsMod, so technically I still own the code.

**Comment by LoopFreedom** [comment]
"This has not breached the TFM licence (As its not a TF Project) and also has not breached your own license (That you clearly copied from the TFM licence) as the authors have not been mis-represented or otherwise." What wild said

**Comment by tylerhyperHD** [comment]
This is your last warning until I DMCA you successfully.

**Comment by LoopFreedom** [comment]
I have to say tylerulties is a nice mod,  i forked it anywyas

**Comment by JeromSar** [comment]
@tylerhyperHD Your project violates TFM's license, more on this later.
